[package]
name = "picopb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arraystring = "0.3.0"
bytes = "1.5.0"
convert_case = "0.6.0"
leb128 = "0.2.5"
pest = "2.7.5"
pest_derive = "2.7.5"
